In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,roc_auc_score,confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("customer_churn_cleaned.csv")

In [3]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85     No  
1               Mailed check          56.95       1889.50     No  
2               Mailed check          53.85        108.15    Yes  
3  Bank transfer (automatic)          42.30       1840.75     No  
4           Electronic check          70.70        151.65    Yes  

[5 rows x 21 columns]

In [4]:
df.tail()

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
7038              Yes               Mailed check          84.80       1990.50   
7039              Yes    Credit card (automatic)         103.20       7362.90   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40        306.60   
7042              Yes  Bank transfer (automatic)         105.65       6844.50   

      Churn  
7038     No  
7039     No  
7040     No  
7041    Yes  
7042     No  

[5 rows x 21 columns]

In [5]:
df.shape

(7043, 21)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [7]:
df.describe()


SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7043.000000
mean        0.162147    32.371149       64.761692   2281.916928
std         0.368612    24.559481       30.090047   2265.270398
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    402.225000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3786.600000
max         1.000000    72.000000      118.750000   8684.800000

In [8]:
df['tenure_group'] = pd.cut(
    df['tenure'],
    bins=[0, 6, 12, 24, 72],
    labels=['0-6', '6-12', '12-24', '24+']
)


In [9]:
df['avg_monthly_spend'] = df['TotalCharges'] / df['tenure']
df['avg_monthly_spend'] = df['avg_monthly_spend'].fillna(0)


In [10]:
services = [
    'PhoneService', 'InternetService', 'OnlineSecurity',
    'OnlineBackup', 'DeviceProtection', 'TechSupport',
    'StreamingTV', 'StreamingMovies'
]

df['num_services_used'] = df[services].apply(
    lambda x: (x == 'Yes').sum(),
    axis=1
)


In [11]:
df['auto_payment_flag'] = df['PaymentMethod'].apply(
    lambda x: 1 if 'automatic' in x.lower() else 0
)


In [12]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ...        Contract  \
0  No phone service             DSL             No  ...  Month-to-month   
1                No             DSL            Yes  ...        One year   
2                No             DSL            Yes  ...  Month-to-month   
3  No phone service             DSL            Yes  ...        One year   
4                No     Fiber optic             No  ...  Month-to-month   

  PaperlessBilling              PaymentMethod MonthlyCharges TotalCharges  \
0              Yes           Electronic check          29.85        29.85   
1               No               Mailed check          56.95      1889.50   
2              Yes               Mailed check          53.85       108.15   
3               No  Bank transfer (automatic)          42.30      1840.75   
4              Yes           Electronic check          70.70       151.65   

  Churn tenure_group avg_monthly_spend  num_services_used  auto_payment_flag  
0    No          0-6         29.850000                  1                  0  
1    No          24+         55.573529                  3                  0  
2   Yes          0-6         54.075000                  3                  0  
3    No          24+         40.905556                  3                  1  
4   Yes          0-6         75.825000                  1                  0  

[5 rows x 25 columns]

In [13]:
X = df.drop(columns=["customerID", "Churn"])
y = df["Churn"]


In [14]:
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_idx, test_idx in sss.split(X, y):
    Churn_train, Churn_test = X.iloc[train_idx], X.iloc[test_idx]
    Churn1_train, Churn1_test = y.iloc[train_idx], y.iloc[test_idx]


In [15]:
print(y.value_counts(normalize=True))
print(Churn_train.value_counts(normalize=True))
print(Churn_test.value_counts(normalize=True))


Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64
gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  MultipleLines  InternetService  OnlineSecurity       OnlineBackup         DeviceProtection     TechSupport          StreamingTV          StreamingMovies      Contract        PaperlessBilling  PaymentMethod            MonthlyCharges  TotalCharges  tenure_group  avg_monthly_spend  num_services_used  auto_payment_flag
Male    0              No       No          1       Yes           No             No               No internet service  No internet service  No internet service  No internet service  No internet service  No internet service  Month-to-month  No                Mailed check             20.20           20.20         0-6           20.200000          1                  0                    0.000711
Female  0              No       No          1       Yes           No             No               No internet service  No internet service  No internet s

In [16]:
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
cat_cols = ['Contract', 'PaymentMethod', 'InternetService','tenure_group']


In [17]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])


In [18]:
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown="ignore"))
])


In [19]:
preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
    
])

In [20]:
churn_prepared = preprocessor.fit_transform(Churn_train)

In [21]:
print(churn_prepared)

[[ 0.10237124 -0.52197565 -0.26328906 ...  0.          1.
   0.        ]
 [-0.71174346  0.33747781 -0.50481448 ...  1.          0.
   0.        ]
 [-0.79315493 -0.80901319 -0.75121344 ...  1.          0.
   0.        ]
 ...
 [-0.30468611  1.25666162  0.15756931 ...  0.          1.
   0.        ]
 [-0.34539184 -1.47766135 -0.79843405 ...  1.          0.
   0.        ]
 [-1.07809507 -1.46936546 -0.96242195 ...  0.          0.
   0.        ]]


# Logistic Regression

In [22]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)
model.fit(churn_prepared,Churn1_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [55]:
Churn_test_prepared = preprocessor.transform(Churn_test)


In [48]:
Churn_prediction_lg = model.predict(Churn_test_prepared)


In [49]:
Churn_prediction_lg

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [50]:
Churn1_test

437     No
2280    No
2235    No
4460    No
3761    No
        ..
5143    No
4439    No
3857    No
4758    No
5613    No
Name: Churn, Length: 1409, dtype: object

In [51]:
cm = confusion_matrix(Churn1_test, Churn_prediction_lg)
cm

array([[756, 279],
       [ 83, 291]], dtype=int64)

In [28]:
print(classification_report(Churn1_test, Churn_prediction_lg))


              precision    recall  f1-score   support

          No       0.90      0.73      0.81      1035
         Yes       0.51      0.78      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.75      0.71      1409
weighted avg       0.80      0.74      0.76      1409



# GradientBoosting Classifier

In [29]:
gb = GradientBoostingClassifier(random_state=42)
smote = SMOTE(random_state=42)
Churn_train_gbs,Churn1_train_gbs= smote.fit_resample(churn_prepared,Churn1_train)
gb.fit(Churn_train_gbs, Churn1_train_gbs)

GradientBoostingClassifier(random_state=42)

In [38]:
gb_preds = gb.predict(Churn_test_prepared)

In [39]:
gb_preds

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [47]:
from sklearn.metrics import confusion_matrix  # re-imported due to overwritten issue
cm = confusion_matrix(Churn1_test, gb_preds)
cm

array([[764, 271],
       [ 75, 299]], dtype=int64)

In [44]:
print(classification_report(Churn1_test,gb_preds))

              precision    recall  f1-score   support

          No       0.91      0.74      0.82      1035
         Yes       0.52      0.80      0.63       374

    accuracy                           0.75      1409
   macro avg       0.72      0.77      0.72      1409
weighted avg       0.81      0.75      0.77      1409



# Random Forest Classifier

In [53]:
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf.fit(churn_prepared, Churn1_train)

RandomForestClassifier(class_weight='balanced', n_estimators=300, n_jobs=-1,
                       random_state=42)

In [57]:
rf_prediction = rf.predict(Churn_test_prepared)

In [58]:
rf_prediction

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [59]:
from sklearn.metrics import confusion_matrix  # re-imported due to overwritten issue
cm = confusion_matrix(Churn1_test, rf_prediction)
cm

array([[895, 140],
       [188, 186]], dtype=int64)

In [60]:
print(classification_report(Churn1_test,rf_prediction))

              precision    recall  f1-score   support

          No       0.83      0.86      0.85      1035
         Yes       0.57      0.50      0.53       374

    accuracy                           0.77      1409
   macro avg       0.70      0.68      0.69      1409
weighted avg       0.76      0.77      0.76      1409



In [ ]:
# need to do roc_auc!!!